version: '3'
services:
  mock-mosaic-maker:
    image: ryanjvanvoorhis/mock-mosaic-maker
    environment:
      - MOSAIC_API_URL=${MOSAIC_API_URL_INTERNAL}
    ports:
      - ${MOCK_MOSAIC_EXTERNAL_PORT}:5080

  mosaic-api:
    build: .
    image: ryanjvanvoorhis/mosaic-api:${BUILD_TIME}
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${MONGODB_URI}
      # - AWS_SESSION_TOKEN=${}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_EXTERNAL_URL=${S3_EXTERNAL_URL}
      - MOSAIC_API_URL_INTERNAL=${MOSAIC_API_URL_INTERNAL}
      - MOSAIC_API_URL_EXTERNAL=${MOSAIC_API_URL_EXTERNAL}
      - FRONT_END_URL=${FRONT_END_URL}
      - FAAS_URL=${FAAS_URL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ENVIRONMENT=test
    ports:
      - ${MOSAIC_API_PORT}:5000

  local-s3:
    # user: root
    image: andrewgaul/s3proxy
    ports:
      - ${S3_PORT}:80
    environment:
      - S3PROXY_AUTHORIZATION=none

  mongodb:
    user: root
    image: bitnami/mongodb
    ports:
      - ${MONGODB_PORT}:27017
