version: '3'
services:

  ### Replace Open_FaaS when running outside of swarm mode
  mock-mosaic-maker:
    image: ryanjvanvoorhis/mock-mosaic-maker
    ports:
      - "5080:5080"

  mosaic-api:
    build: .
    image: ryanjvanvoorhis/mosaic-api
    environment:
      - MONOGODB_URI=mongodb://mongodb:27017/
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - FRONT_END_URL=http://localhost:8081
      - FAAS_URL=http://mock-mosaic-maker:5080
      - S3_ENDPOINT_URL=http://local-s3:80/
      - S3_EXTERNAL_URL=http://localhost:80
      - MOSAIC_API_URL_INTERNAL=http://mosaic-api:5000/api/v1/photomosaic
      - MOSAIC_API_URL_EXTERNAL=http://${BROADCAST_IP}:5000/api/v1/photomosaic
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "5000:5000"

### DATA ###
  local-s3:
    user: root
    image: andrewgaul/s3proxy
    ports:
      - "80:80"
    environment:
      - S3PROXY_AUTHORIZATION=none
    volumes:
      - /opt/local_s3:/data

  mongodb:
    user: root
    image: 'bitnami/mongodb:latest'
    ports:
      - "27018:27017"
    volumes:
      - /opt/mongodb:/bitnami